### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by melfriedman** [learn-co-curriculum/dsc-intro-to-sets-lab#3]
Found a tiny typo in one of the directions/prompts. 
![image](https://user-images.githubusercontent.com/68208636/97652091-db8f3700-1a1a-11eb-9233-75baee03fc1a.png)

On the last line, Mary is spelled as Marie.

**Comment by Cheffrey2000** [comment]
This issue has been resolved

**Comment by jessepisel** [comment]
This issue has been resolved here https://github.com/learn-co-curriculum/dsc-intro-to-sets-lab/commit/c3c427235f637411f82fb347f08222d7d059d163
